SELECT 
    CONCAT(CEIL(MONTH(DIFFERENTIATION_DATE) / 3.0), 'Q') AS QUARTER,
    COUNT(ID) AS ECOLI_COUNT
FROM 
    ECOLI_DATA
GROUP BY 
    CONCAT(CEIL(MONTH(DIFFERENTIATION_DATE) / 3.0), 'Q')
ORDER BY CONCAT(CEIL(MONTH(DIFFERENTIATION_DATE) / 3.0), 'Q')
